### ISSUE TITLE
مشکل با ایرنا

### ISSUE THREAD

**Issue by mardetanha** [5j9/citer#12]
من امروز هرچه تلاش کردم سایتر لینکی برای ایرنا نمی‌ساخت.
لینک مثل 
https://www.irna.ir/news/83408885/%D9%85%D8%B1%DA%AF-%D8%A8%D9%88%DA%A9%D8%B3%D9%88%D8%B1-%D8%B1%D9%88%D8%B3-%D9%BE%D8%B3-%D8%A7%D8%B2-%D8%B6%D8%B1%D8%A8%D9%87-%D9%81%D9%86%DB%8C-%D8%B4%D8%AF%D9%86-%D8%AF%D8%B1-%D8%B1%D8%A7%D9%86%D8%AF-%DB%8C%D8%A7%D8%B2%D8%AF%D9%87%D9%85
با تشکر

**Comment by 5j9** [comment]
به نظر میرسه وب‌گاه ایرنا در خارج از ایران در دسترس نیست.
در
https://www.isitdownrightnow.com/irna.ir.html
هم "Irna.ir is DOWN for everyone." را نشان می‌دهد. 

در toolforge:

```
$ wget www.irna.ir
--2019-07-25 07:10:49--  http://www.irna.ir/
Resolving www.irna.ir (www.irna.ir)... 185.143.232.5, 185.143.234.5, 185.143.233.5
Connecting to www.irna.ir (www.irna.ir)|185.143.232.5|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.irna.ir/ [following]
--2019-07-25 07:10:52--  https://www.irna.ir/
Connecting to www.irna.ir (www.irna.ir)|185.143.232.5|:443... connected.
ERROR: The certificate of ‘www.irna.ir’ is not trusted.
ERROR: The certificate of ‘www.irna.ir’ hasn't got a known issuer.
```

<div dir=rtl>
نشانی دامنه هم قابل دستیابی نبود:
</div>

```

$ nslookup www.irna.ir
;; Got SERVFAIL reply from 208.80.154.143, trying next server
Server:         208.80.154.24
Address:        208.80.154.24#53

** server can't find www.irna.ir: SERVFAIL
```

<div dir=rtl>
امیدوارم این مشکل مقطعی باشد و خودش حل شود. (متأسفانه اگر نباشد هم به نظرم استفاده از پراکسی‌های ایرانی به دردسرهای آن نمی‌رازد).
</div>

**Comment by mardetanha** [comment]
اره درسته، خیلی عجیبه چون موقعی که من کار میکردم در دسترس بود ولی الان نیست. ممنونم
