### ISSUE TITLE
New Google Books interface and URLs

### ISSUE THREAD

**Issue by daniel-barrows** [5j9/citer#15]
## Description
Google Books has a new interface, described in a [blog post](https://www.blog.google/products/search/15-years-google-books/) and in [documentation](https://support.google.com/websearch/answer/9523832?hl=en).

## URL Changes
They have changed their URLs accordingly, like this:

* Old version aka. Classic Google Books
  * https://books.google.com/books?id=bwfoCAAAQBAJ&pg=PA32
* New Google Books
  * https://www.google.com/books/edition/The_Formative_Years_of_R_G_Collingwood/bwfoCAAAQBAJ?gbpv=1&pg=PA32

Note that the title part of the URL is ignored, but cannot be omitted.
* These work
  * https://www.google.com/books/edition/_/bwfoCAAAQBAJ?gbpv=1&pg=PA32
  * https://www.google.com/books/edition/arbitrary-text/bwfoCAAAQBAJ?gbpv=1&pg=PA32
* These do not work
  * https://www.google.com/books/edition//bwfoCAAAQBAJ?gbpv=1&pg=PA32
  * https://www.google.com/books/edition/bwfoCAAAQBAJ?gbpv=1&pg=PA32

## Transition history
Starting around autumn 2019, the new interface became publicly available as an opt-in option. Starting about April 2020, it became the default but the new interface included a button to opt out and return to the old interface. As of today, 7 May 2020, I'm not seeing the opt out button, but URL links to the old interface still show up in the old interface. I suspect at some point, these links to the old interface are going to redirect to the new interface.

## What this means for citer
As a regular user of citer, I have been sticking with the old interface so I can easily copy and paste the URLs into citer. If the old interface is shutdown and URLs are redirected, which seems immanent, then this will no longer possible. Even now, without an opt-out button to return to the old interface, it is not trivial to obtain a URL that can be input into Citer.

### High priority
Please allow citer to parse Google Books URLs in the new format.

### Low priority
We may also want to consider generating URLs in the new format. There are enough URLs live on the internet that it seems very likely to me that Google Books would continue to support them or redirect to an equivalent page in the new URL pattern. Therefore, there is no urgency to this change. However, it is probably a good idea to minimize redirects and make new features more readily available to the readers who click on these links.

**Comment by 5j9** [comment]
Thanks for the thorough bug report.

I don't know why, but I cannot switch to the new UI. Every time I click on the "Try it now" button it reloads the same page with the same "Try the new Google Books" prompt at the top. Also the new URLs all redirect me to the old format. E.g. https://www.google.com/books/edition/The_Formative_Years_of_R_G_Collingwood/bwfoCAAAQBAJ?gbpv=1&pg=PA32 redirects me to https://books.google.com/books?id=bwfoCAAAQBAJ&newbks=0&printsec=frontcover&pg=PA32#v=onepage&q&f=false .

Anyway, I've updated Citer to support the new URL format you've mentioned. Let me know if you notice any issues.

Regarding the output URL format (Low priority), I have not decided how to proceed yet. Normalizing the output urls is a little complicated and I'm not sure if it is worth it. All the following urls are valid:
1. https://encrypted.google.com/books?id=6upvonUt0O8C
2. https://www.google.com/books?id=bwfoCAAAQBAJ&pg=PA32
3. https://www.google.com/books/edition/_/bwfoCAAAQBAJ?gbpv=1&pg=PA32
4. https://books.google.com/books?id=pzmt3pcBuGYC
5. https://books.google.de/books?id=pzmt3pcBuGYC
6. https://books.google.co.il/books?id=pzmt3pcBuGYC
7. ...

Google has a ton of other similar domains for google books and I prefer to keep language-specific domains unchanged in the output...

**Comment by 5j9** [comment]
I decided to continue to return the `https://books.google.com/books?id=<volumeid>` format which is the one returned by Google Book's citation generator (BibTex/EndNote/RefMan) for now. I'll definitely consider changing this if google updates its citation format.
