### ISSUE TITLE
support for JSTOR

### ISSUE THREAD

**Issue by fgnievinski** [5j9/citer#25]
this doesn't seem to work:

https://www.jstor.org/stable/30078788

I get "An unknown error occurred."

**Comment by 5j9** [comment]
It should be working now. However since this is a new feature it might fail in some cases. Let me know if you find anything wrong in the results.

**Comment by fgnievinski** [comment]
it works great, many thanks! 

may I suggest including the following field: 

jstor=30078788

here's a usage example:

https://en.wikipedia.org/wiki/Lloyd's_mirror

**Comment by 5j9** [comment]
Done! ;)

**Comment by fgnievinski** [comment]
hi again.  it seems that non-ASCII characters would need some work?

for example:

https://www.jstor.org/stable/40991855

the journal is titled "Revista Geográfica" but it's misrecognized as "Revista GeogrÃ¡fica"

thanks!
