### ISSUE TITLE
theses and dissertations in dspace

### ISSUE THREAD

**Issue by fgnievinski** [5j9/citer#27]
many theses and dissertations are hosted in institutional repositories running dspace, for example:

https://repositorio.unesp.br/handle/11449/86528

unfortunately, it's cited as a website, missing important information about the publisher (university).

**Comment by fgnievinski** [comment]
related issue: some dspaces result in an unknown error in citer, for example:

https://lume.ufrgs.br/handle/10183/29131

https://citer.toolforge.org/citer.fcgi?user_input=https%3A%2F%2Fciter.toolforge.org%2Fciter.fcgi%3Finput_type%3Durl-doi-isbn%26user_input%3Dhttps%253A%252F%252Flume.ufrgs.br%252Fhandle%252F10183%252F29131%26dateformat%3D%2525Y-%2525m-%2525d&dateformat=%25B%20%25-d%2C%20%25Y

**Comment by fgnievinski** [comment]
> related issue: some dspaces result in an unknown error in citer, for example:

the part above is fixed:

https://citer.toolforge.org/citer.fcgi?input_type=url-doi-isbn&user_input=https%3A%2F%2Flume.ufrgs.br%2Fhandle%2F10183%2F29131&dateformat=%25B+%25-d%2C+%25Y

**Comment by fgnievinski** [comment]
a new subproblem is the date. for example, here it should be 2012, but it's reported as 2013:

https://lume.ufrgs.br/handle/10183/67061

here's the relevant metadata:

```
<meta name="DCTERMS.dateAccepted" content="2013-02-27T01:39:58Z" xml:lang="pt_BR" scheme="DCTERMS.W3CDTF" />
<meta name="DCTERMS.issued" content="2012" xml:lang="pt_BR" scheme="DCTERMS.W3CDTF" />
```

it seems date issued should be used instead of date accepted.

**Comment by 5j9** [comment]
This issue is mostly fixed. `publisher` and `date` are now collected from the respective meta tags. However, the result is still a `cite web` template. Unfortunately I dont think there is any easy way to fix the citation type here as there are no meta tags to infer a better citation type.
