### ISSUE TITLE
Bug: USA Today citations have "Today, USA" as second author

### ISSUE THREAD

**Issue by madprogramer** [5j9/citer#28]
Hey!

I was just wondering why no one has made a good open source tool for online citations yet, and discovered citer **today!** 

So in appreciation for all of your hard work, have a bug report!

![image](https://user-images.githubusercontent.com/3719664/124365552-82367200-dc51-11eb-959f-0f1e49c2044e.png)

Because of how the [webpage](https://www.usatoday.com/story/entertainment/movies/2019/11/12/star-wars-disney-plus-changes-controversial-han-solo-greedo-scene/2576097001/) is formatted, "USA Today" gets captured as the second author, together with Brian Truitt.

```
<ref name="Truitt Today 2019">{{cite web | last=Truitt | first=Brian | last2=Today | first2=Usa | title=The infamous 'Han shot first' scene in 'Star Wars' has changed yet again on Disney+ | website=USA TODAY | date=2019-11-12 | url=https://www.usatoday.com/story/entertainment/movies/2019/11/12/star-wars-disney-plus-changes-controversial-han-solo-greedo-scene/2576097001/ | access-date=2021-07-03}}</ref>
```

I can actually look into forking and fixing this myself next week, if no one else beats me to it!
Cheers!

**Comment by 5j9** [comment]
I can't figure out why the fix works on my machine but not on toolforge.

**Comment by madprogramer** [comment]
Staged roll-out! You gotta love it, but you also just have to hate it sometimes :}

**Comment by 5j9** [comment]
> Maybe there could be two implementations to check which version of the site the client is on?

Yeah, but I'm trying to avoid adding site-specific rules... For now, I decided to ignore all uppercase author names. I hope it won't cause too many false negatives. 🤞

**Comment by daniel-barrows** [comment]
All-uppercase surnames are commonly used in East Asian names to clarify which of the names is to be regarded as a surname, as many East Asian cultures haven't standardized the representation or order of names in Latin Script. See, for example, Robinson, Emily Claire. (2006). _[A guide to names and naming practices](https://www.fbiic.gov/public/2008/nov/Naming_practice_guide_UK_2006.pdf)_. Government of the United Kingdom / Interpol General Secretariat.
