### ISSUE TITLE
The OCLC # query does not seem to be working

### ISSUE THREAD

**Issue by Peaceray2** [5j9/citer#39]
When I use the OCLC # query, I get a "An unknown error occurred." message in the Shortened footnote and citation field

**Comment by 5j9** [comment]
Unfortunately worldcat.org has made some changes recently that makes it very hard for bots/web crawlers to explore their website. Citer is not currently capable of handling these new restrictions. I was not able to find any other web service that provides citation information for OCLC numbers. At this point I will probably need to drop support for OCLC and worldcat URLs :(

**Comment by 5j9** [comment]
Apparently worldcat.org has removed some the restrictions mentioned earlier. This seems to be working right now. If an error is still showing up for you, please provide the specific OCLC # that is failing so I can investigate more into it.
