### ISSUE TITLE
"Unknown Error Occured" also for URLs, similar to OCLC report

### ISSUE THREAD

**Issue by danshearer** [5j9/citer#40]
Thought it might be helpful to know that I seem to get the same result as #39 , only for URLs too.

DOI works fine. 

Thanks, Citer is very handy.

**Comment by 5j9** [comment]
Thank you!
I tried a few worldcat URLs of some journals today, they seem to work most of the time (sometimes the server responds too late and a timeout error occurs, so one may need to give it 2-3 tries).

If you have a specific URL that constantly fails in several retries, please provide that specific URL so I can look into what's happening.
