### ISSUE TITLE
NYTimes blocks bots

### ISSUE THREAD

**Issue by reagle** [5j9/citer#42]
Hello, I have a similar python scraper using requests, and when I want to fetch the title I'm given useless HTML stating "Please enable JS and disable any ad blocker". I'm wondering if you manage to get the date and title of nytimes.com content, how you do so? Could you point me to the code? (I had a quick look, but didn't see anything specific to nytimes beyond the tests.)

**Comment by 5j9** [comment]
Hi! I can reproduce, but unfortunately could not figure out how nytimes works. 

On one of my PCs adding a user-agent header to the get request solved the issue, but on another one it didn't. The strange thing is that running a simple `curl` command in the terminal works on both of these computers. There might be some caching mechanism involved. IDK.

P.S
I suspect they a have whitelist for `curl` user-agent. Try this:
```pyhton
requests.get('https://www.nytimes.com/2023/03/29/world/americas/fire-mexico-migrants.html', headers={
        "User-Agent": "curl/7.54"
    }).text
```
this also worked on both PCs.

**Comment by reagle** [comment]
Thanks, I ended up [adopting the  API](https://github.com/reagle/thunderdell/blob/main/formats/scrape/nytimes.py), but it's good to know this `user-agent` gets the job done too -- for now.
