### ISSUE TITLE
Name value within ref tag

### ISSUE THREAD

**Issue by badgettrg** [5j9/citer#44]
This is a great resource. Consider following, or giving an option to use, the informal convention that many wiki editors use in naming references in order to reduce the chaos of a study being cited with more than one tag in an article.

<ref name = "pmid12345678">

or if no PMID, 

<ref name = "doi10.1001/jama.290.2.215">

**Comment by 5j9** [comment]
I'm not familiar with this convention. Could you provide some examples?

**Comment by 5j9** [comment]
I've changed the re-name generation mechanism to a semi-random 5-letter string. I know that this is against the recommendation of [WP:REFNAME](https://en.wikipedia.org/wiki/Help:Footnotes#WP:REFNAME) which states that "Names should have semantic value", but it's hard to come up with a general algorithm that produces a meaningful, unique, and yet concise reference name. I may revert this change if I get negative feedback from users.
