### ISSUE TITLE
Citer does not properly handle PhD dissertations

### ISSUE THREAD

**Issue by lihaohong6** [5j9/citer#47]
Hi 5j9! Thank you for creating such a wonderful tool. I stumbled upon an issue where citer cannot handle the link to a dissertation. For example, [this link](https://dl.acm.org/doi/10.5555/1123678) results in an error in citer. Is there a way to handle this web page (and similar publications) to use the {{cite thesis}}? Thanks!

**Comment by 5j9** [comment]
Hi! Thank you!

The main issue with https://dl.acm.org/ was that their server is returning [`403` response code](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403) to any request from toolforge's IP address. The same URL is accessible from my PC. This usually means that they have blacklisted toolforge's IP address (perhaps after some bots/tools sent too many requests to their server). I have configured citer to use citoid in when the usual URL resolver fails.

> Is there a way to handle this web page (and similar publications) to use the {{cite thesis}}?

This particular website should be working now, but if citer is failing for other similar publications, then it is likely that there is some other issue involved. I will investigate if such cases get reported.
