### ISSUE TITLE
JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

### ISSUE THREAD

**Issue by grimes2** [5j9/citer#48]
Add [10.1038/532432a](https://doi.org/10.1038%2F532432a) Result: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

**Comment by 5j9** [comment]
Sorry guys. Apparently doi.org has blacklisted toolforge's IP address due to large number of requests sent. I'm working on it.

**Comment by 5j9** [comment]
A workaround has been implemented. Let me know if it does not work for you.

**Comment by grimes2** [comment]
Same error message with OCLC.

**Comment by 5j9** [comment]
> Same error message with OCLC.

Fixed.
