### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by fgnievinski** [5j9/citer#56]
with the following URL:

https://books.google.com.br/books?id=XrgyEAAAQBAJ&newbks=1&newbks_redir=0&dq=%22free+vector%22+bound+vector&source=gbs_navlinks_s

**Comment by 5j9** [comment]
When I click on the "EndNote" button at end of that page to export the citation in RIS format, I get a 404-error page. That's basically how citer currently retrieves citation information for google books. If the google books server for some reason fails to provide citation information, citer will also fail. Sorry, but I don't think I can fix this one.

![image](https://github.com/user-attachments/assets/cfd207c1-91cd-49ee-bfdc-46ecc485ce88)

![image](https://github.com/user-attachments/assets/fe4cd733-dfb1-4801-aa8c-fc189f23d844)
