### ISSUE TITLE
PMIDs and tag names

### ISSUE THREAD

**Issue by badgettrg** [5j9/citer#60]
Great tool. I will be soon closing https://sumsearch.org/cite/ and am looking for another option.

Consider adding the PMID parameter and value to your citation output. Linking the reader to the NLM gives them additional knowledge discovery tools such as links to similar or citing articles.

Consider an alternative tag name attribute, such as pmid12345678 (where 12345678 is the article's PMID) or the same with a DOI if the article is not available at the NLM.
The standardized name may reduce the frequency of inadvertent duplicate citations on wiki pages.

**Comment by 5j9** [comment]
Hi, thanks for your suggestions! Could you please provide a more specific example of the input you'd like to see the PMID parameter in the output? Citer currently supports PMIDs, but you'll need to select 'PMID' from the dropdown menu at the top to specify the input type.

The generated names should be unique, with duplicates being very rare. If you've encountered any instances of duplicate names generated by Citer, please let me know so I can investigate and make improvements.

**Comment by badgettrg** [comment]
The input options are fine. The role of the PMID is in the value the ref tag.

See example at an alternative citation maker:
https://citation-template-filling.toolforge.org/cgi-bin/index.cgi?ddb=&type=pubmed_id&id=38424346&add_ref_tag=1

By having a predictable ref value, "pmid#######" where ####### is the article's actual PMID, you avoid the problem that has plagued WikiPedia in the past where an article will have multiple entries in the bibliography because each citation in the uses a differing value of the ref tag.

bob
________________________________

**Comment by 5j9** [comment]
I don't think that issue applies to Citer. Although Citer's reference names are semi-random, they are deterministic. This means that for a given PMID, the reference name will always be the same, ensuring that identical PMIDs appear as the same entry in the bibliography.

**Comment by badgettrg** [comment]
Yes, but you are not using the convention of other citation makers and so citer will create a second reference in the bibliography of pages if a prior wiki author on the same page used a citation maker that uses the pmid######## standard.

bob

On Oct 25, 2024, at 2:50 AM, 5j9 ***@***.***> wrote:

﻿

Closed #60<https://github.com/5j9/citer/issues/60> as completed.

**Comment by 5j9** [comment]
Ah, I see what you mean.  While that approach might work for PMIDs, I don't think it's suitable for DOIs in general. Many DOIs are quite long, such as `10.1371/annotation/56ccf999-c461-4598-a883-55fbac9751a6`, which would look visually unappealing as reference names.

In the end, the need for a bot/script to clean-up all citations within a long article might be inevitable as someone could have created a citation for the same PMID but with a different ref name manually. I wish this ref-name generation business could somehow be handled within the citation template itself. 😩
