### ISSUE TITLE
Shortened footnote buttons don't work when input provided by URL

### ISSUE THREAD

**Issue by daniel-barrows** [5j9/citer#63]
When you provide input to Citer via URL rather than by form, the "Copy sfn" and "Copy citation" buttons don't work.

## Directions to reproduce bug in Copy citation
1. Go to https://citer.toolforge.org/?user_input=978-1-509-54622-0
2. Click "Copy citation"
3. Paste output

Expected output:
````
* {{cite book | last=Ferdinand | first=Malcom | title=A Decolonial Ecology | publisher=Polity | publication-place=Cambridge, UK Medford, MA | date=18 January 2022 | isbn=978-1-5095-4622-0}}
````
Actual output
````
undefined
````

## Directions to reproduce bug in Copy sfn
1. Go to https://citer.toolforge.org/?user_input=978-1-509-54622-0
2. Click "Copy sfn"
3. Paste output

Expected output:
````
{{sfn|Ferdinand|2022|p=}}
````
Actual output
````
{{sfn|Ferdinand|2022|p=}}* {{cite book | last=Ferdinand | first=Malcom | title=A Decolonial Ecology | publisher=Polity | publication-place=Cambridge, UK Medford, MA | date=18 January 2022 | isbn=978-1-5095-4622-0}}
````

## Cause
https://citer.toolforge.org/static/en973342032.js attempts to obtain the component parts by splitting the `#shortened` contenteditable by "\n\n". When the citation is generated on the server-side and delivered in the HTML, the citation is instead split by `<br><br>`. Thus, the whole `#shortened` contenteditable is regarded as the first part (sfn), leaving the second part empty (citation).

**Comment by daniel-barrows** [comment]
I failed to report that the "Copy" button of the `#shortened` contenteditable is broken as well, although less dramatically. The `<br>` tags are not preserved when the clipboard is pasted into a text editor, so the resulting output is identical to what I reported above for the "Copy sfn" button.

**Comment by 5j9** [comment]
Should be fixed now. Thanks for all the thorough bug reports.
